In [94]:
import pandas as pd
import numpy as np

In [95]:
df = pd.read_csv('spotify_data.csv')

In [96]:
df.head()

,Position,Track Name,Artist,Streams,URL,Date,Region
0,1,Reggaetón Lento (Bailemos),CNCO,19272,https://open.spotify.com/track/3AEZUABDXNtecAO...,2017-01-01,ec
1,2,Chantaje,Shakira,19270,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,2017-01-01,ec
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,https://open.spotify.com/track/3QwBODjSEzelZyV...,2017-01-01,ec
3,4,Vente Pa' Ca,Ricky Martin,14954,https://open.spotify.com/track/7DM4BPaS7uofFul...,2017-01-01,ec
4,5,Safari,J Balvin,14269,https://open.spotify.com/track/6rQSrBHf7HlZjtc...,2017-01-01,ec

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3441197 entries, 0 to 3441196
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   Position    int64
 1   Track Name  object
 2   Artist      object
 3   Streams     int64
 4   URL         object
 5   Date        object
 6   Region      object
dtypes: int64(2), object(5)
memory usage: 183.8+ MB

In [98]:
df.describe()

           Position       Streams
count  3.441197e+06  3.441197e+06
mean   9.464399e+01  5.189176e+04
std    5.739567e+01  2.018035e+05
min    1.000000e+00  1.001000e+03
25%    4.500000e+01  3.322000e+03
50%    9.200000e+01  9.227000e+03
75%    1.430000e+02  2.965800e+04
max    2.000000e+02  1.138152e+07

In [99]:
df.isnull().sum()

Position        0
Track Name    657
Artist        657
Streams         0
URL             8
Date            0
Region          0
dtype: int64

In [100]:
df.dropna(inplace=True)

In [101]:
df.isnull().sum()

Position      0
Track Name    0
Artist        0
Streams       0
URL           0
Date          0
Region        0
dtype: int64

In [102]:
df.drop(['URL'],inplace=True,axis=1)

In [103]:
df.shape

(3440540, 6)

In [104]:
df.head()

,Position,Track Name,Artist,Streams,Date,Region
0,1,Reggaetón Lento (Bailemos),CNCO,19272,2017-01-01,ec
1,2,Chantaje,Shakira,19270,2017-01-01,ec
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,2017-01-01,ec
3,4,Vente Pa' Ca,Ricky Martin,14954,2017-01-01,ec
4,5,Safari,J Balvin,14269,2017-01-01,ec

In [105]:
df.columns

Index(['Position', 'Track Name', 'Artist', 'Streams', 'Date', 'Region'], dtype='object')

In [106]:
df['Artist'].value_counts()

Ed Sheeran          127064
The Chainsmokers     68321
Drake                49054
Calvin Harris        38460
Imagine Dragons      37992
                     ...
Pugh Rogefeldt           1
Mikael Rickfors          1
Snowstorm                1
Lasse Berghagen          1
帶菌者                      1
Name: Artist, Length: 6628, dtype: int64

In [107]:
artist_list = df.groupby('Artist')['Streams'].sum().index.tolist()
artist_list

['#TocoParaVos',
 '$uicideBoy$',
 '*NSYNC',
 '-M-',
 '070 Shake',
 '100%',
 '101Barz',
 '10cm',
 '12:00',
 '13 Block',
 '13 Crowns',
 '16yrold',
 '187 Strassenbande',
 '1987',
 '1Kilo',
 '2 Chainz',
 '21 Savage',
 '22 Savage',
 '24Heavy',
 '257ers',
 '2NE1',
 '2Pac',
 '3 Doors Down',
 '30Y',
 '3robi',
 '4 Non Blondes',
 '4Keus Gang',
 '5 After Midnight',
 '50 Cent',
 '53A',
 '5MIINUST',
 '5NAPBACK',
 '6150',
 '6LACK',
 '6cyclemind',
 '6ix9ine',
 '77 Bombay Street',
 '80KIDZ',
 '88GLAM',
 '9 Miller',
 '98º',
 'A Boogie Wit da Hoodie',
 'A Great Big World',
 'A R I Z O N A',
 'A Si',
 'A Tribe Called Quest',
 'A$AP Ferg',
 'A$AP Mob',
 'A$AP Rocky',
 "A'typisk",
 'A-Lin',
 'A-Mei Chang',
 'A-Trak',
 'A-do',
 'AAA',
 'ABBA',
 'ABREU',
 'AC/DC',
 'ACIDMAN',
 'AC周予天',
 'ADHD',
 'AGA',
 'AGNEZ MO',
 'AI',
 'AJ Tracey',
 'AJR',
 'AK',
 'AK Ausserkontrolle',
 'AKB48',
 'AKDONG MUSICIAN',
 'AKKOGORILLA',
 'AKLO',
 'ALIUS',
 'ALMA',
 'ALP',
 'AM',
 'AMiR',
 'ANDREZO',
 'ANNA',
 'AOA',
 'AREA21',
 'ARLE',
 'ARY',
 'ASIAN KUNG-FU GENERATION',
 'AURORA',
 'AWOLNATION',
 'AX 13',
 'Aaron Carter',
 'Abbaz',
 'Abdul & The Coffee Theory',
 'Abel Pintos',
 'Abou Debeing',
 'Abra',
 'Abra Cadabra',
 'Abraham Mateo',
 'Acantilados',
 'Acapellago',
 'Ace',
 'Ace Wilder',
 'Ace of Base',
 'Achey',
 'Achille Lauro',
 'Ada',
 'Ada Band',
 'Adam Davenport',
 'Adam Lambert',
 'Adam Levine',
 'Adam Mitchell',
 'Adam Naas',
 'Adamlar',
 'Adason Lo',
 'Adel',
 'Adel Tawil',
 'Adele',
 'Adelén',
 'Aden',
 'Adera',
 'Adhitia Sofyan',
 'Adi L Hasla',
 'Adinda Shalahita',
 'Adje',
 'Admiral P',
 'Adolf Fredriks Musikklasser',
 'Adolf Fredriks Ungdomskör',
 'Adolf Fredriks kyrkas kammarkör',
 'Adolfo Echeverria',
 'Adolphe Adam',
 'Adolphson & Falk',
 'Adoo',
 'Adrees',
 'Adrian Khalif',
 'Adrijana',
 'Adventure Club',
 'Ady Suleiman',
 'Aegis',
 'Aerosmith',
 'Afgan',
 'Afro Bros',
 'Afrojack',
 'Agapornis',
 'Agir',
 'Agnes Stock',
 'Agnieszka Chylinska',
 'Agoney',
 'Agus Padilla',
 'Ahmad Jais',
 'Ahmet Şafak',
 'Ai Otsuka',
 'Aikakone',
 'Ailee',
 'Aiman Tino',
 'Aimer',
 'Aishah',
 'Aitana Ocaña',
 'Aiza Seguerra',
 'Aizat Amdan',
 'Ajda Pekkan',
 'Akai Ko-en',
 'Akcent',
 'Akim',
 'Akim And The Majistret',
 'Aknestik',
 'Akon',
 'Aksel & Hef',
 'Al Bano',
 'Al Green',
 'Al James',
 'Alabama Shakes',
 'Alan Silvestri',
 'Alan Tam',
 'Alan Walker',
 'Albert Dyrlund',
 'Alberto Ciccarini',
 'Albin Johnsén',
 'Albin Lee Meldau',
 'Alcides',
 'Aldair Playboy',
 'Aldy Maldini',
 'Aled Jones',
 'Aleete',
 'Alejandro Fernandez',
 'Alejandro Sanz',
 'Aleks',
 'Aleksanteri Hakaniemi',
 'Alessandra Amoroso',
 'Alessia Cara',
 'Alessio Bernabei',
 'Alesso',
 'Alex',
 'Alex & Sierra',
 'Alex Adair',
 'Alex Aiono',
 'Alex Badilla',
 'Alex Bueno',
 'Alex Ceesay',
 'Alex Christensen',
 'Alex Da Kid',
 'Alex Fong',
 'Alex Gaudino',
 'Alex Mattson',
 'Alex Rose',
 'Alex Ross',
 'Alex Sensation',
 'Alex Ubago',
 'Alex Vargas',
 'Alex Zurdo',
 'Alexa',
 'Alexander Brown',
 'Alexander Jarl',
 'Alexander Lewis',
 'Alexander Oscar',
 'Alexander Wilde',
 'Alexandra Joner',
 'Alexandra Stan',
 'Alexio',
 'Alexis y Fido',
 'Alextbh',
 'Aleyna Tilki',
 'Alf Prøysen',
 'Alfred Beach Sandal',
 'Alfred García',
 'Alfred Hui',
 'Alfred Sim',
 'Alfredo Olivas',
 'Ali As',
 'Ali B',
 'Ali Bumaye',
 'Aliando Syarief',
 'Alice',
 'Alice DJ',
 'Alice Merton',
 'Alicia Keys',
 'Alida',
 'Alien Ant Farm',
 'Alif Satar',
 'Aliff Aziz',
 'Alina Devecerski',
 'Aliotta Haynes Jeremiah',
 'Alisah Bonaobra',
 'Alkaline',
 'Alkilados',
 'All Saints',
 'All Star Cast',
 'All Time Low',
 'Allame',
 'Allday',
 'Alle Farben',
 'Allie X',
 'Alligatoah',
 'Allman Brown',
 'Allyawan',
 'Alma',
 'Alma Africana',
 'Aloe Blacc',
 'Alok',
 'Alonzo',
 'Alphabeat',
 'Alta Consigna',
 'Altimet',
 'AlunaGeorge',
 'Alvaro',
 'Alvaro Soler',
 'Alvin Ng',
 'Alyssa Reid',
 'Alzate',
 'AmPm',
 'Amaia Romero',
 'Aman Shah',
 'Amanda',
 'Amanda Delara',
 'Amanda Fondell',
 'Amanda Jenssen',
 'Amar Azul',
 'Amaral',
 'Amco',
 'Amedeo Preziosi',
 'Amelia van Hootens',
 'Amelina',
 'Amenazzy',
 'American Authors',
 'Amerie',
 'Aminé',
 'Amir',
 'Ammunition',
 'Amy Macdonald',
 'Amy Shark',
 'Amy Winehouse',
 'Américo',
 'Ana Diaz',
 'Ana Guerra',
 'Ana Mena',
 'Ana Vilela',
 'Anavitória',
 'And Then Came Fall',
 'Anders Ekborg',
 'Anders Hemmingsen',
 'Anders Matthesen',
 'Anders Nilsen',
 'Anderson',
 'Anderson .Paak',
 'Andien',
 'Andra & The Backbone',
 'Andra Day',
 'Andre Hazes',
 'Andre Hehanussa',
 'Andrea Bocelli',
 'Andrea Gylfadóttir',
 'Andrea Radice',
 'Andreas Aleman',
 'Andreas Gabalier',
 'Andreas Moe',
 'Andreas Weise',
 'Andrelli',
 'Andrew Belle',
 'Andrew Billings',
 'Andrew McMahon in the Wilderness',
 'Andrew Tan',
 'André Hazes Jr.',
 'Andrés Calamaro',
 'Andrés Cepeda',
 'Andrés Suárez',
 'Andy Grammer',
 'Andy Hui',
 'Andy Lau',
 'Andy Rivera',
 'Andy Shauf',
 'Andy Williams',
 'Andymori',
 'Ane Brun',
 'Anevo',
 'Angel',
 'Angela Chang',
 'Angela Torres',
 'Angeles',
 'Angelica Vale',
 'Angelina Jordan',
 'Angeline Quinto',
 'Angelo King',
 'Angemi',
 'Angerwolf',
 'Anggun',
 'Angie Stone',
 'Angus & Julia Stone',
 'Angèle',
 'Ania Dabrowska',
 'Ania Wyszkoni',
 'Aniceto Molina',
 'Aniceto Molina Y La Luz Roja De San Marcos',
 'Anine Stang',
 'Anis Don Demina',
 'Anita Kerr Singers',
 'Anitta',
 'Anja Nissen',
 'Anji',
 'Anjulie',
 'Anly',
 'Anna Eriksson',
 'Anna Järvinen',
 'Anna Kendrick',
 'Anna Naklab',
 'Anna Of The North',
 'Anna Puu',
 'Anna Ternheim',
 'Annalisa',
 'Anne Grete Preus',
 'Anne Linnet',
 'Anne-Marie',
 'AnnenMayKantereit',
 'Annet Charitonová',
 'Annie Leigh',
 'Annie Lennox',
 'Anniina',
 'Annika Wells',
 'Annikki Tähti',
 'Anoflex',
 'Anonimus',
 'Anouk',
 'Ansiktet',
 'Ansis',
 'Anson Hu',
 'Anssi Kela',
 'Anstandslos & Durchgeknallt',
 'Anthony',
 'Anthony Gonzalez',
 'Anthony Harm',
 'Antilopen Gang',
 'Antis',
 'Anton Hagman',
 'Anton Powers',
 'Antonello Venditti',
 'Antonio José',
 'Antonio Orozco',
 'Antonio Rios',
 'Antony Parviainen',
 'Antti Ketonen',
 'Antti Railio',
 'Antti Tuisku',
 'Anu-D',
 'Anuar & Ellina',
 'Anuar Zain',
 'Anuel Aa',
 'Anıl Piyancı',
 'Apink',
 'Apollo LTD',
 'Apres Ski Allstars',
 'April Ivy',
 'April Red 紅',
 'Apulanta',
 'Aquilo',
 'Ara Johari',
 'Arash',
 'Arcade Fire',
 'Arcadian',
 'Arcangel',
 'Architechs',
 'Architrackz',
 'Arctic Monkeys',
 'Ardhito Pramono',
 'Ardian Bujupi',
 'Arena Hash',
 'Ares',
 'Aretha Franklin',
 'Ari Koivunen',
 'Ari Lasso',
 'Ariadne',
 'Ariana Grande',
 'Ariel Camacho y Los Plebes Del Rancho',
 'Ariel Tsai',
 'Arif',
 'Arin Ray',
 'Arisa',
 'Arizona Jones',
 'Arja Koriseva',
 'Arkells',
 'Arlissa',
 'Armada',
 'Arman Cekin',
 'Armand Maulana',
 'Armand Van Helden',
 'Armando Hernandez',
 'Armin van Buuren',
 'Armoo',
 'Aron Brink',
 'Aron Can',
 'Aron Hannes',
 'AronChupa',
 'Arop',
 'Arshad Maimouni',
 'Art Garfunkel',
 'Artem x Yonas',
 'Artful Dodger',
 'Artigeardit',
 'Artists for Grenfell',
 'Artsvik',
 'Arttu Lindeman',
 'Arttu Wiskari',
 'Arturo "Zambo" Cavero',
 'Arty',
 'Arvingarna',
 "As'ad Motawh",
 'Asa',
 'Asako Toki',
 'Ash Kidd',
 'Ashafar',
 'Ashanti',
 'Ashley Lovechild',
 'Aska Yang',
 'Aslove',
 'Aste',
 'Astrid S',
 'At17',
 'Athena',
 'Atitude 67',
 'Atiye',
 'Atle',
 'Atmosfera',
 'Atomic Kitten',
 'Atomic Otro Way',
 'Atomirotta',
 'Attan',
 'Attaque 77',
 'Attractions',
 'Au/Ra',
 'Audioslave',
 'August Alsina',
 'August Dahl',
 "Auli'i Cravalho",
 'Aura',
 'Aurora',
 'Austin Basham',
 'Austin Lee',
 'Austin Mahone',
 'Austyn Johnson',
 'Av. Larco, la película',
 'Avain',
 'Avelino',
 'Aventura',
 'Avicii',
 'Avril Lavigne',
 'Awich',
 'Axel',
 'Axel Schylström',
 'Axos',
 'Axwell',
 'Axwell /\\ Ingrosso',
 'Aya Nakamura',
 'Ayben',
 'Ayda Jebat',
 'Aydın Kurtoğlu',
 'Aylin Coşkun',
 'Ayo',
 'Ayo & Teo',
 'Ayse Hatun Onal',
 'Ayten Alpman',
 'Ayşegül Aldinç',
 'Azad',
 'Azet',
 'Aziz Harun',
 'Azlina Aziz',
 'Azucar Moreno',
 'Azzi Memo',
 'B Young',
 'B*Witched',
 'B-Brave',
 'B.A.P',
 'B.B. King',
 'B.o.B',
 'B2K',
 'BACALL',
 'BAD HOP',
 'BAEKHYUN',
 'BANANALEMON',
 'BASTIAN',
 'BAYNK',
 'BC Unidos',
 'BCW',
 'BEATEN FAME',
 'BEK & Wallin',
 'BESS',
 'BIGBANG',
 'BJ The Chicago Kid',
 'BK',
 'BKO',
 'BLACKPINK',
 'BLVK JVCK',
 'BLØF',
 'BMYE',
 'BONNIE X CLYDE',
 'BOOM BOOM SATELLITES',
 'BOXING樂團',
 'BOY STORY',
 'BRADIO',
 'BROADHURST',
 'BROCKHAMPTON',
 'BSMG',
 'BTOB',
 'BTS',
 'Baaba Maal',
 'Baby Bash',
 'Baby K',
 'Bacilos',
 'Backstreet Boys',
 'Baco Exu do Blues',
 'Bad Bunny',
 'Bad Gyal',
 'BadBadNotGood',
 'Badoxa',
 'Badpojken',
 'Bae Fong',
 'Bag Raiders',
 'Baggalútur',
 'Bahadır Tatlıöz',
 'Bahamas',
 'Bailey May',
 'Baka Not Nice',
 'Bakarhythm To',
 'Bakermat',
 'Balsam Boys',
 'Bambini Di Praga',
 'Bamboo',
 'Bamse',
 'Band Aid',
 'Band Aid 20',
 'Band Aid 30',
 'Band of Horses',
 'Banda Conmoción',
 'Banda El Recodo',
 'Banda Los Recoditos',
 'Banda Neira',
 'Banda Sinaloense MS de Sergio Lizárraga',
 'Banda Tierra Sagrada',
 'Banda XXI',
 'Bang For The Buck',
 'BangBros',
 'Banks',
 'Banu Parlak',
 'Bar Z',
 'Barbra Streisand',
 'Barenaked Ladies',
 'Barnens önskejul artister',
 'Barnkammarkören',
 'Barry Manilow',
 'Bars and Melody',
 'Bart Peeters',
 'Bartofso',
 'Barış Manço',
 'Base Ball Bear',
 'BasedBoys',
 'Basement Jaxx',
 'Basenji',
 'Basic Tape',
 'Basim',
 'Bassbros',
 'Basshunter',
 'Bassi Maestro',
 'Bassjackers',
 'Bastian',
 'Bastille',
 'Battle Beast',
 'Bausa',
 'Baustelle',
 'Bazart',
 'Bağzıları',
 'Bca',
 'Bea Miller',
 'Bearson',
 'Beatrice Eli',
 'Beatrich',
 'Beatriz Luengo',
 'Beatsteaks',
 'Bebe',
 'Bebe Rexha',
 'Becca Adams',
 'Beck',
 'Becky G',
 'Becky Hill',
 'Bedoes',
 'Bee Gees',
 'Beegie Adair & Friends',
 'Beginner',
 'Bek Phillips',
 'Beko',
 'Belchior',
 'Belinda Carlisle',
 'Bella & Filippa',
 'Ben Cristovao',
 'Ben DJ',
 'Ben E. King',
 'Ben Howard',
 'Ben Mitkus',
 'Ben Rector',
 'Ben Sihombing',
 'Ben&Ben',
 'Benal',
 'Benash',
 'Benedicté',
 'Bengous',
 'Bengü',
 'Benjamin',
 'Benjamin Beats',
 'Benjamin Blümchen',
 'Benjamin Clementine',
 'Benjamin Francis Leftwich',
 'Benjamin Ingrosso',
 'Benjamin Rihan',
 'Benjamín Amadeo',
 'Benji & Fede',
 'Benni Sparks',
 'Benny Anderssons Orkester',
 'Benny Jamz',
 'Bente',
 'Beret',
 'Berkay',
 'Berkcan Güven',
 'Berksan',
 'Bermudu Divstūris',
 'Bernhoft',
 'Bet Bet',
 'Beta Radio',
 'Beth Ditto',
 'Betta Lemme',
 'Bette Midler',
 'Betty Who',
 'Betül Demir',
 'Beverly',
 'Beyoncé',
 'Bhad Bhabie',
 'Bianca Atzei',
 'Bianca Ryan',
 'Białas',
 'Białas, Lanek',
 'Bibi H.',
 'Biffy Clyro',
 'Big Boi',
 'Big Boy',
 'Big Fish',
 'Big Scary',
 'Big Sean',
 'Big Shaq',
 'Big Sim',
 'Big Wild',
 'Big Yamo',
 'Bigflo & Oli',
 'Bil Musa',
 'Bilal Hancı',
 'Bilal Sonses',
 'Bilderbuch',
 'Bile-Dani',
 'Bilge Nihan',
 'Bill Withers',
 'Billie Eilish',
 'Billie Holiday',
 "Billo's Caracas Boys",
 'Billy Currington',
 'Billy Joel',
 'Billy Paul',
 'Billy Raffoul',
 'Bing Crosby',
 'Bingo Players',
 'Binomio de Oro de América',
 'Biondo',
 'Bipolar Sunshine',
 'Birdy',
 'Birgir',
 'Birgitta Haukdal',
 'Birnir',
 'Birol Giray',
 'Bishop Briggs',
 'Bispo',
 'Bizzey',
 'Björgvin Halldórsson',
 'Björk',
 'Björk Guðmundsdóttir',
 'Björn Skifs',
 'Bjørnskov',
 'Black',
 'Black Box',
 'Black Dog Bone',
 'Black M',
 'Black Saint',
 'BlackJack',
 'Blackstreet',
 'Blak',
 'Blake Shelton',
 'Blanche',
 'Blas Cantó',
 'Bleachers',
 'Blen',
 'Bliss n Eso',
 'Blizzy',
 'Block B',
 'Blonde',
 'Blonde Redhead',
 'Blossoms',
 'Blouson Chiemi',
 'Blu Cantrell',
 'Blue',
 'Blue Cafe',
 'Blue Cafe & Kornelia Mzyk',
 'Blue Street Players',
 'Blue Swede',
 'Blue Öyster Cult',
 'Blur',
 'Bo Kaspers Orkester',
 'BoA',
 'Bob B. Soxx & The Blue Jeans',
 'Bob Dylan',
 'Bob Marley & The Wailers',
 'Bob Pressner',
 'Bob Sinclar',
 'Bobby "Boris" Pickett',
 'Bobby "Boris" Pickett & The Crypt-Kickers',
 'Bobby Darin',
 'Bobby Helms',
 'Bobby McFerrin',
 'Bobby Vee',
 'Bobby Vinton',
 'Boef',
 'Boehm',
 'Bohemia Suburbana',
 'Bokoesam',
 'Boku no Lyric no Boyomi',
 'Bolier',
 'Bollebof',
 'Bolly',
 'Bomba Estéreo',
 'Bombai',
 'Bombay Bicycle Club',
 'Bon Iver',
 'Bon Jovi',
 'Bonde R300',
 'Boney M.',
 'Bonez MC',
 'Bonnie Tyler',
 'Bonny Cepeda',
 'Bonny Lovy',
 'Bonobo',
 'Boo Seeka',
 'Booba',
 'Boomdabash',
 'Boostee',
 'Boreal',
 'Boris René',
 'Borixon',
 'Bosx1ne',
 'Boudewijn de Groot',
 'Bovea Y Sus Vallenatos',
 'BowlLane Slick',
 'Boyat',
 'Boys Under The Moon',
 'Boyz II Men',
 'Boyzone',
 'Brad Paisley',
 'Brainstorm',
 'Brandon Beal',
 'Brandyn Burnette',
 'Branko',
 'Brantley Gilbert',
 'Breakbot',
 'Breathe Carolina',
 'Brenda Lee',
 'Brendan Murray',
 'Brett Eldredge',
 'Brett Young',
 'Brian Eno',
 'Brian Ligon',
 'Brian McKnight',
 'Briga',
 'Brings',
 'Britney Spears',
 'Bro',
 'Broadcast',
 'Broederliefde',
 'Broertje',
 'Broiler',
 'Broken Back',
 'Brolle',
 'Bronco',
 'Brooke Candy',
 'Bruce Reitherman',
 'Bruce Springsteen',
 'Bruninho & Davi',
 'Bruno & Barretto',
 'Bruno & Marrone',
 'Bruno Mars',
 'Bruno Martini',
 'Bruno Wintzell',
 'Brunori Sas',
 'Bryan Adams',
 'Bryant Myers',
 'Bryson Tiller',
 'Brytiago',
 'Brädi',
 'Bubbi Morthens',
 'Bugzy Malone',
 'Buitres',
 'Bulin 47',
 'Bunbury',
 'Bunga Citra Lestari',
 'Burak King',
 'Burak Yeter',
 'Buray',
 'Burcu Güneş',
 'Burhan G',
 'Burl Ives',
 'Burna Boy',
 'Bushido',
 'Busta Rhymes',
 'Busted',
 'Busungarna',
 'Busy P',
 'By2',
 'BÖ',
 'BØRNS',
 'Büyük Ev Ablukada',
 'C AllStar',
 'C&K',
 'C-bool',
 'C. Tangana',
 'CASPR',
 'CAZZETTE',
 'CD9',
 'CHAI',
 'CHANMINA',
 'CHANO',
 'CHEMISTRY',
 'CHEN',
 'CHIC',
 'CHICO CARLITO',
 'CHO',
 'CJaye',
 'CLAIRE',
 'CLMD',
 'CLOVES',
 'CLiQ',
 'CMC$',
 'CMX',
 'CNCO',
 'CUT_',
 'CVBZ',
 'Cabas',
 'Caesars',
 'Café Quijano',
 'Café Tacvba',
 'Cage The Elephant',
 'Caifanes',
 'Cakra Khan',
 'Cal',
 'Cal Scruby',
 'Calcutta ',
 'Caleb Santos',
 'Calema',
 'Cali Flow Latino',
 'Cali Y El Dandee',
 'Calibre 50',
 'Calin',
 'Callalily',
 'Calle 13',
 'Callejeros',
 'Calling Mercury',
 'Callum Beattie',
 'Caloncho',
 'Calum Scott',
 'Calvert Fu',
 'Calvin Harris',
 'CamelPhat',
 'Camila',
 'Camila Cabello',
 'Camila Gallardo',
 'Camille Cabaltera',
 'Campsite Dream',
 'Can Bonomo',
 'Can Gox',
 'Can Güngör',
 'Can Kazaz',
 'Can Oflaz',
 'Can Yüce',
 'Candi Staton',
 'Candy Lo',
 'Canesecco',
 'CantoParaBailar',
 'Caparezza',
 'Capital Bra',
 'Capital Cities',
 'Capo',
 'Capo Plaza',
 'Cappella Snöstorp',
 'Caramelos De Cianuro',
 'Cardenales De Nuevo León',
 'Cardi B',
 'Carina Dahl',
 'Carl Brave x Franco 126',
 'Carl Cox',
 'Carl Louis',
 'Carla Bruni',
 'Carla Morrison',
 'Carlitos Rossy',
 'Carlos Baute',
 'Carlos Rivera',
 'Carlos Roman',
 'Carlos Sadness',
 'Carlos Vives',
 'Carly Rae Jepsen',
 'Carlão',
 'Carmon',
 'Carnie And Wendy Wilson',
 'Carnival Youth',
 'Carola',
 'Carolina Deslandes',
 'Caroline Castell',
 'Caroline Henderson',
 'Caroline Selma',
 'Carpark North',
 'Carpenters',
 'Cartel De Santa',
 'Cascada',
 'Cash Cash',
 'Cashmere Cat',
 'Casper',
 'Cass McCombs',
 'Cassie',
 'Cassow',
 "Cast Of 'Brødrene Mortensens Jul'",
 'Cast Of Rent',
 'Cat Ballou',
 'Cat Dealers',
 'Catfish and the Bottlemen',
 'Catupecu Machu',
 'Causes',
 'Cavalier',
 'Cazzi Opeia',
 'Cazzu',
 'CeCe Peniston',
 'Cecilia Kallin',
 'Cedric Gervais',
 'CeeLo Green',
 'Ceky Viciny',
 'Celest Cheung',
 'Celia Cruz',
 'Celia Cruz y La Sonora Matancera',
 ...]

In [108]:
artist_streams = df.groupby('Artist')['Streams'].sum().values.tolist()
artist_streams

[3485730,
 44258,
 7484201,
 43037,
 31035,
 2465,
 81269,
 247144,
 6706,
 853726,
 8652,
 235239,
 88355831,
 23914,
 74279422,
 358556483,
 1127824035,
 12126721,
 7525,
 6365229,
 118844,
 716046,
 6518,
 28905,
 5764078,
 61852,
 3699534,
 3172245,
 848913,
 7124,
 4115,
 114472,
 22805,
 119658667,
 9302224,
 50635445,
 28150,
 14968,
 2299597,
 550516,
 1245395,
 391855170,
 493845,
 95312726,
 30625,
 1102,
 227104708,
 24892547,
 987827,
 635003,
 3249817,
 4203630,
 209745,
 368076,
 8449246,
 1045267,
 1378067,
 4363602,
 7657,
 22625,
 490000,
 2124026,
 642067,
 821221,
 816299,
 411364919,
 17519,
 9745920,
 6738,
 106603,
 192694,
 180374,
 35511,
 58592067,
 768043,
 545163,
 2751,
 343288,
 127590,
 22837,
 2433,
 40728,
 213681,
 228310,
 6768,
 62733,
 637898,
 71103630,
 71306,
 105367,
 9663038,
 543770,
 488435,
 139855,
 155964727,
 3152,
 28796,
 32823,
 2503861,
 9365,
 27131,
 9016753,
 8072,
 7012237,
 1180,
 3211,
 4234035,
 65444,
 68869,
 4965589,
 2193,
 4345107,
 20081575,
 329947476,
 123941,
 1272122,
 3692710,
 637422,
 2127757,
 31182,
 1186211,
 26914,
 165301,
 50812,
 111013,
 45872,
 162833,
 4075910,
 288615,
 58898,
 34568,
 1905589,
 161765,
 79262,
 25399,
 439927,
 136066,
 485889,
 6034277,
 3693421,
 201206,
 19336,
 25673,
 49592,
 355714,
 136070,
 216584,
 14025,
 20459,
 1482890,
 2263728,
 1938919,
 54172,
 2087741,
 99927,
 158311,
 622431,
 17692,
 25166,
 64462,
 7027,
 12170,
 122959,
 1352249,
 96494,
 86841,
 524485,
 1269,
 46648,
 3723,
 719416330,
 5599773,
 489578,
 146884,
 48194,
 21542,
 227186,
 2035098,
 630276,
 7820,
 117316361,
 26452536,
 25061,
 13312690,
 2351737,
 692886045,
 705729,
 38682170,
 2805,
 7399844,
 41324,
 116234,
 85578,
 1044,
 39309,
 314613,
 189578,
 379821,
 150139,
 594899,
 2379480,
 2064442,
 239418711,
 788903,
 79116,
 12418,
 65653,
 9885,
 372044,
 1418,
 55886,
 17036,
 1507664,
 274752,
 22071,
 7069026,
 7116,
 9312543,
 143336,
 28680,
 145042,
 586011,
 51940,
 28855714,
 1384583,
 24275890,
 12460281,
 22858,
 777873,
 20510,
 37214293,
 2016762,
 1663100,
 89181,
 649511,
 3511,
 15434,
 4194,
 34245,
 459117,
 5965049,
 184755,
 62929,
 51753,
 994595,
 292258,
 42610921,
 251172,
 999392,
 1481,
 394865,
 82731,
 18515,
 426631,
 558044707,
 35101392,
 490118,
 40064891,
 312260,
 729075,
 1409119,
 6388526,
 5924,
 746770,
 327410,
 512238,
 3349013,
 34243,
 15121035,
 3818878,
 26071,
 1484112,
 502414,
 14529,
 2345,
 2006050,
 53494,
 3484,
 517881,
 155181,
 172831,
 256150727,
 2376771,
 10652,
 425272,
 17231916,
 837138,
 306571,
 33872,
 892154,
 7977307,
 6228817,
 122730176,
 4659,
 694064,
 76169,
 1061722,
 60754,
 113410,
 1097,
 36777,
 3458526,
 1164232,
 239979,
 1203424,
 111589,
 2552,
 238717,
 429532,
 2257462,
 24333,
 1976284,
 1576966,
 2484,
 70529,
 180473,
 819237,
 6068391,
 4403311,
 4118209,
 17353,
 99700715,
 2439,
 24891,
 4197958,
 76311,
 75934323,
 1167,
 117696,
 202920,
 63000,
 13748,
 98064,
 633294,
 2383894,
 69692,
 6194607,
 428156,
 451786,
 11961,
 80593,
 67735,
 9897085,
 250095,
 825752,
 54485,
 27363,
 16391,
 13511,
 777581,
 33254514,
 337681910,
 199998,
 3250027,
 4513604,
 57611,
 41271,
 29652,
 1975475,
 3951,
 60662,
 2323594,
 131886,
 2760441,
 32875,
 570487,
 158685692,
 479478,
 20285,
 90311,
 327998,
 927535,
 15762,
 7975,
 246215,
 233221,
 16788,
 652832,
 30936,
 50284,
 124005,
 366589,
 6938,
 2106644,
 3917,
 651467,
 1075,
 6651548,
 1381168,
 361693,
 27090983,
 162317,
 95290,
 45301,
 1230206,
 65216,
 35956315,
 257985,
 195702,
 485753,
 427617361,
 15836,
 9821,
 10276,
 31722,
 32160,
 3452,
 110565,
 46574,
 2703432,
 180863,
 1558181,
 105084,
 61393175,
 97399,
 3803631,
 44240584,
 31941,
 125158,
 28994,
 65623,
 2116783,
 37270,
 1155254,
 15387,
 777476150,
 9332574,
 7967,
 7544465,
 30394,
 34246,
 3140,
 47474,
 27588,
 274743,
 11597837,
 4743837,
 20531,
 38955,
 11417,
 17780297,
 7136622,
 51229,
 4486350,
 162192,
 4053157,
 45476,
 19571,
 161104,
 412670,
 95802,
 245298,
 3286020,
 18562,
 7067388,
 8007080,
 192720,
 65373,
 82767,
 478335,
 9785,
 76396,
 141107,
 400606,
 39115,
 10898,
 286311,
 42874,
 7771276,
 89546290,
 24666,
 2023218,
 959309,
 135305,
 68113,
 2044337,
 58698,
 55279,
 32694,
 1116071,
 641609,
 46647,
 20506,
 6444126,
 149475,
 106213,
 20661993,
 81715,
 336879,
 3114,
 7235,
 1213933,
 1772796,
 523323,
 79037,
 57928,
 1046,
 847296911,
 228079,
 138190,
 340481,
 2493446,
 396286,
 27596,
 784980958,
 7416569,
 464021,
 597595,
 1767740,
 99933,
 49972,
 179539463,
 6541625,
 9512,
 56827,
 1270894,
 22022839,
 376351,
 28874,
 31510,
 14645827,
 615995,
 103368,
 721504,
 11763,
 43396,
 92283,
 42517,
 1772439,
 15004,
 16919,
 7242,
 3951,
 50388,
 35628,
 32951,
 8450,
 2144299,
 3615476,
 7174675,
 1262,
 49216,
 2142599,
 26434297,
 3129,
 3671952,
 2010048,
 12681,
 13246,
 41009,
 3095,
 2853,
 15482,
 302335,
 34258,
 7744,
 216496126,
 3807,
 16720,
 16861248,
 24443459,
 3892991,
 191228,
 457239767,
 3752842,
 3058,
 20774,
 71435,
 77679,
 30958799,
 389263,
 2781835,
 4242,
 535134,
 6028138,
 2577,
 7854177,
 47672,
 60247,
 30063,
 20959,
 80433413,
 79651,
 3104001,
 54565,
 11109,
 1726613,
 4749932,
 2679040,
 82139094,
 217872,
 325655,
 2271047,
 2122234,
 26170,
 43322,
 21162,
 119286,
 32512,
 31464,
 29527,
 263140,
 1228,
 3057,
 1162223,
 28126,
 17907,
 4030077,
 147009,
 30098,
 516042,
 7389923,
 202084,
 132644,
 81812,
 2816,
 110381,
 21038345,
 12364,
 102232535,
 1291794,
 2119204,
 2120072,
 37251,
 38563,
 125946,
 67095,
 99869,
 2483313,
 43791,
 24817,
 580350195,
 13505,
 338781,
 366797512,
 44938,
 2622282,
 2676736,
 11301,
 10077143,
 20722,
 439871,
 422228,
 46851,
 2137685,
 959718,
 303450,
 173483,
 447580,
 139671,
 177833,
 13606,
 505677,
 760644,
 16603494,
 2758,
 61847,
 4897047,
 55598,
 4338452,
 24375,
 2099,
 190219,
 7645167,
 53693,
 46373,
 9762938,
 50722,
 2057369,
 2290492,
 13503,
 23178689,
 3001861,
 225872,
 448790,
 24133,
 29625,
 1165,
 7130,
 9807,
 39052,
 3316,
 2780,
 111585,
 46833,
 12110479,
 192643,
 889770,
 688415,
 3152543,
 149212,
 627548,
 1071977,
 8916,
 1078,
 3269,
 30998,
 864370365,
 196795965,
 7599,
 2531,
 183191,
 20543452,
 11876,
 222851,
 22686,
 2627693,
 9728,
 1763717,
 107797,
 989093,
 28518,
 94215,
 10665225,
 459319,
 39872,
 3193,
 105573146,
 51558,
 24825,
 174471,
 42566,
 551492,
 115218,
 149185,
 1572827,
 6145,
 6986,
 205224,
 35746510,
 130991,
 65794,
 2691,
 51908,
 24907,
 155821,
 46094,
 76630,
 2728836,
 712295,
 210577,
 4236187,
 12854400,
 349832,
 7194228,
 1258901,
 3235,
 18213,
 17766040,
 247415,
 3135,
 1355945,
 13811,
 34243,
 88413,
 286569,
 103414,
 62614,
 13957,
 39317,
 50184,
 1404687,
 390789,
 481450,
 3712,
 437598,
 404671,
 529827,
 188347,
 416920,
 214616,
 1828455,
 80565,
 24755987,
 198766,
 3924,
 36295,
 139713545,
 261552,
 11829,
 1628656,
 10999,
 63398,
 69355,
 5146,
 508085,
 3986369,
 41342,
 937071,
 950549,
 18600109,
 10237774,
 149845585,
 850463,
 11079,
 1236187,
 765516,
 18252,
 92133682,
 4852947,
 6212177,
 132538,
 2619389,
 79401,
 521447,
 14401,
 13649,
 4359,
 134269,
 6624,
 432542,
 7937310,
 9121,
 1260,
 905143,
 37376,
 1607,
 1363771,
 48687,
 92738,
 79735942,
 17109,
 2235479,
 54438316,
 1280,
 4393,
 40370,
 1886624,
 339712,
 19662490,
 1981658,
 26385,
 68437247,
 810793,
 6920543,
 924126,
 687341,
 448941,
 44482,
 3303,
 9011653,
 44451635,
 32677,
 10059859,
 1915554926,
 27013336,
 522021,
 541201,
 7305328,
 20904622,
 218894798,
 49500976,
 4254984,
 29679,
 5930769,
 3610,
 31824,
 223149,
 569640,
 4625378,
 324151134,
 7992590,
 208512,
 1927642,
 50009973,
 97974,
 37882837,
 214418,
 163824,
 914034,
 1102292,
 24043,
 6429,
 320439,
 169343,
 728334,
 2709,
 1343548,
 49316958,
 42062,
 85035,
 6277571,
 4182,
 580476,
 12957922,
 123424,
 72916,
 77356,
 3295,
 73125,
 530579,
 1945,
 766577,
 43516,
 981464,
 590245,
 10520,
 1051701848,
 6969,
 196695,
 875525,
 163635,
 1815089,
 11050344,
 56163,
 8565463,
 757164,
 28094,
 22880,
 3707614,
 351031,
 1414598,
 3866,
 148299889,
 22940858,
 68373,
 5592777,
 59926,
 13740691,
 6820,
 78169,
 3128626,
 62393726,
 6299,
 2397708371,
 21380570,
 72561,
 1704460390,
 5873246,
 21658,
 226421,
 4546568,
 1651088,
 174656,
 1050997,
 47688,
 837938,
 87300,
 90248,
 441888,
 3920234,
 12607875,
 75336372,
 510163,
 60032946,
 34553926,
 30426,
 1679,
 48649,
 488584021,
 14580,
 13391826,
 2985,
 11221,
 43035,
 7955029,
 698701,
 75849593,
 25298776,
 10435,
 50145,
 462191473,
 2036011,
 156827,
 4785512,
 263778,
 7838,
 4896930,
 491902,
 360754,
 263358,
 9798,
 9139,
 12172387,
 60685442,
 42158,
 58920845,
 123439052,
 6057364,
 44585,
 87558,
 412448,
 92803,
 1821,
 104862,
 1224352,
 17099,
 3566759,
 551583,
 4510,
 23236,
 8940809,
 48712,
 3242,
 4263,
 75915,
 242298,
 70022,
 14238,
 314884,
 ...]

In [109]:
artist = dict(zip(artist_list,artist_streams))

In [110]:
artist

{'#TocoParaVos': 3485730,
 '$uicideBoy$': 44258,
 '*NSYNC': 7484201,
 '-M-': 43037,
 '070 Shake': 31035,
 '100%': 2465,
 '101Barz': 81269,
 '10cm': 247144,
 '12:00': 6706,
 '13 Block': 853726,
 '13 Crowns': 8652,
 '16yrold': 235239,
 '187 Strassenbande': 88355831,
 '1987': 23914,
 '1Kilo': 74279422,
 '2 Chainz': 358556483,
 '21 Savage': 1127824035,
 '22 Savage': 12126721,
 '24Heavy': 7525,
 '257ers': 6365229,
 '2NE1': 118844,
 '2Pac': 716046,
 '3 Doors Down': 6518,
 '30Y': 28905,
 '3robi': 5764078,
 '4 Non Blondes': 61852,
 '4Keus Gang': 3699534,
 '5 After Midnight': 3172245,
 '50 Cent': 848913,
 '53A': 7124,
 '5MIINUST': 4115,
 '5NAPBACK': 114472,
 '6150': 22805,
 '6LACK': 119658667,
 '6cyclemind': 9302224,
 '6ix9ine': 50635445,
 '77 Bombay Street': 28150,
 '80KIDZ': 14968,
 '88GLAM': 2299597,
 '9 Miller': 550516,
 '98º': 1245395,
 'A Boogie Wit da Hoodie': 391855170,
 'A Great Big World': 493845,
 'A R I Z O N A': 95312726,
 'A Si': 30625,
 'A Tribe Called Quest': 1102,
 'A$AP Ferg': 227104708,
 'A$AP Mob': 24892547,
 'A$AP Rocky': 987827,
 "A'typisk": 635003,
 'A-Lin': 3249817,
 'A-Mei Chang': 4203630,
 'A-Trak': 209745,
 'A-do': 368076,
 'AAA': 8449246,
 'ABBA': 1045267,
 'ABREU': 1378067,
 'AC/DC': 4363602,
 'ACIDMAN': 7657,
 'AC周予天': 22625,
 'ADHD': 490000,
 'AGA': 2124026,
 'AGNEZ MO': 642067,
 'AI': 821221,
 'AJ Tracey': 816299,
 'AJR': 411364919,
 'AK': 17519,
 'AK Ausserkontrolle': 9745920,
 'AKB48': 6738,
 'AKDONG MUSICIAN': 106603,
 'AKKOGORILLA': 192694,
 'AKLO': 180374,
 'ALIUS': 35511,
 'ALMA': 58592067,
 'ALP': 768043,
 'AM': 545163,
 'AMiR': 2751,
 'ANDREZO': 343288,
 'ANNA': 127590,
 'AOA': 22837,
 'AREA21': 2433,
 'ARLE': 40728,
 'ARY': 213681,
 'ASIAN KUNG-FU GENERATION': 228310,
 'AURORA': 6768,
 'AWOLNATION': 62733,
 'AX 13': 637898,
 'Aaron Carter': 71103630,
 'Abbaz': 71306,
 'Abdul & The Coffee Theory': 105367,
 'Abel Pintos': 9663038,
 'Abou Debeing': 543770,
 'Abra': 488435,
 'Abra Cadabra': 139855,
 'Abraham Mateo': 155964727,
 'Acantilados': 3152,
 'Acapellago': 28796,
 'Ace': 32823,
 'Ace Wilder': 2503861,
 'Ace of Base': 9365,
 'Achey': 27131,
 'Achille Lauro': 9016753,
 'Ada': 8072,
 'Ada Band': 7012237,
 'Adam Davenport': 1180,
 'Adam Lambert': 3211,
 'Adam Levine': 4234035,
 'Adam Mitchell': 65444,
 'Adam Naas': 68869,
 'Adamlar': 4965589,
 'Adason Lo': 2193,
 'Adel': 4345107,
 'Adel Tawil': 20081575,
 'Adele': 329947476,
 'Adelén': 123941,
 'Aden': 1272122,
 'Adera': 3692710,
 'Adhitia Sofyan': 637422,
 'Adi L Hasla': 2127757,
 'Adinda Shalahita': 31182,
 'Adje': 1186211,
 'Admiral P': 26914,
 'Adolf Fredriks Musikklasser': 165301,
 'Adolf Fredriks Ungdomskör': 50812,
 'Adolf Fredriks kyrkas kammarkör': 111013,
 'Adolfo Echeverria': 45872,
 'Adolphe Adam': 162833,
 'Adolphson & Falk': 4075910,
 'Adoo': 288615,
 'Adrees': 58898,
 'Adrian Khalif': 34568,
 'Adrijana': 1905589,
 'Adventure Club': 161765,
 'Ady Suleiman': 79262,
 'Aegis': 25399,
 'Aerosmith': 439927,
 'Afgan': 136066,
 'Afro Bros': 485889,
 'Afrojack': 6034277,
 'Agapornis': 3693421,
 'Agir': 201206,
 'Agnes Stock': 19336,
 'Agnieszka Chylinska': 25673,
 'Agoney': 49592,
 'Agus Padilla': 355714,
 'Ahmad Jais': 136070,
 'Ahmet Şafak': 216584,
 'Ai Otsuka': 14025,
 'Aikakone': 20459,
 'Ailee': 1482890,
 'Aiman Tino': 2263728,
 'Aimer': 1938919,
 'Aishah': 54172,
 'Aitana Ocaña': 2087741,
 'Aiza Seguerra': 99927,
 'Aizat Amdan': 158311,
 'Ajda Pekkan': 622431,
 'Akai Ko-en': 17692,
 'Akcent': 25166,
 'Akim': 64462,
 'Akim And The Majistret': 7027,
 'Aknestik': 12170,
 'Akon': 122959,
 'Aksel & Hef': 1352249,
 'Al Bano': 96494,
 'Al Green': 86841,
 'Al James': 524485,
 'Alabama Shakes': 1269,
 'Alan Silvestri': 46648,
 'Alan Tam': 3723,
 'Alan Walker': 719416330,
 'Albert Dyrlund': 5599773,
 'Alberto Ciccarini': 489578,
 'Albin Johnsén': 146884,
 'Albin Lee Meldau': 48194,
 'Alcides': 21542,
 'Aldair Playboy': 227186,
 'Aldy Maldini': 2035098,
 'Aled Jones': 630276,
 'Aleete': 7820,
 'Alejandro Fernandez': 117316361,
 'Alejandro Sanz': 26452536,
 'Aleks': 25061,
 'Aleksanteri Hakaniemi': 13312690,
 'Alessandra Amoroso': 2351737,
 'Alessia Cara': 692886045,
 'Alessio Bernabei': 705729,
 'Alesso': 38682170,
 'Alex': 2805,
 'Alex & Sierra': 7399844,
 'Alex Adair': 41324,
 'Alex Aiono': 116234,
 'Alex Badilla': 85578,
 'Alex Bueno': 1044,
 'Alex Ceesay': 39309,
 'Alex Christensen': 314613,
 'Alex Da Kid': 189578,
 'Alex Fong': 379821,
 'Alex Gaudino': 150139,
 'Alex Mattson': 594899,
 'Alex Rose': 2379480,
 'Alex Ross': 2064442,
 'Alex Sensation': 239418711,
 'Alex Ubago': 788903,
 'Alex Vargas': 79116,
 'Alex Zurdo': 12418,
 'Alexa': 65653,
 'Alexander Brown': 9885,
 'Alexander Jarl': 372044,
 'Alexander Lewis': 1418,
 'Alexander Oscar': 55886,
 'Alexander Wilde': 17036,
 'Alexandra Joner': 1507664,
 'Alexandra Stan': 274752,
 'Alexio': 22071,
 'Alexis y Fido': 7069026,
 'Alextbh': 7116,
 'Aleyna Tilki': 9312543,
 'Alf Prøysen': 143336,
 'Alfred Beach Sandal': 28680,
 'Alfred García': 145042,
 'Alfred Hui': 586011,
 'Alfred Sim': 51940,
 'Alfredo Olivas': 28855714,
 'Ali As': 1384583,
 'Ali B': 24275890,
 'Ali Bumaye': 12460281,
 'Aliando Syarief': 22858,
 'Alice': 777873,
 'Alice DJ': 20510,
 'Alice Merton': 37214293,
 'Alicia Keys': 2016762,
 'Alida': 1663100,
 'Alien Ant Farm': 89181,
 'Alif Satar': 649511,
 'Aliff Aziz': 3511,
 'Alina Devecerski': 15434,
 'Aliotta Haynes Jeremiah': 4194,
 'Alisah Bonaobra': 34245,
 'Alkaline': 459117,
 'Alkilados': 5965049,
 'All Saints': 184755,
 'All Star Cast': 62929,
 'All Time Low': 51753,
 'Allame': 994595,
 'Allday': 292258,
 'Alle Farben': 42610921,
 'Allie X': 251172,
 'Alligatoah': 999392,
 'Allman Brown': 1481,
 'Allyawan': 394865,
 'Alma': 82731,
 'Alma Africana': 18515,
 'Aloe Blacc': 426631,
 'Alok': 558044707,
 'Alonzo': 35101392,
 'Alphabeat': 490118,
 'Alta Consigna': 40064891,
 'Altimet': 312260,
 'AlunaGeorge': 729075,
 'Alvaro': 1409119,
 'Alvaro Soler': 6388526,
 'Alvin Ng': 5924,
 'Alyssa Reid': 746770,
 'Alzate': 327410,
 'AmPm': 512238,
 'Amaia Romero': 3349013,
 'Aman Shah': 34243,
 'Amanda': 15121035,
 'Amanda Delara': 3818878,
 'Amanda Fondell': 26071,
 'Amanda Jenssen': 1484112,
 'Amar Azul': 502414,
 'Amaral': 14529,
 'Amco': 2345,
 'Amedeo Preziosi': 2006050,
 'Amelia van Hootens': 53494,
 'Amelina': 3484,
 'Amenazzy': 517881,
 'American Authors': 155181,
 'Amerie': 172831,
 'Aminé': 256150727,
 'Amir': 2376771,
 'Ammunition': 10652,
 'Amy Macdonald': 425272,
 'Amy Shark': 17231916,
 'Amy Winehouse': 837138,
 'Américo': 306571,
 'Ana Diaz': 33872,
 'Ana Guerra': 892154,
 'Ana Mena': 7977307,
 'Ana Vilela': 6228817,
 'Anavitória': 122730176,
 'And Then Came Fall': 4659,
 'Anders Ekborg': 694064,
 'Anders Hemmingsen': 76169,
 'Anders Matthesen': 1061722,
 'Anders Nilsen': 60754,
 'Anderson': 113410,
 'Anderson .Paak': 1097,
 'Andien': 36777,
 'Andra & The Backbone': 3458526,
 'Andra Day': 1164232,
 'Andre Hazes': 239979,
 'Andre Hehanussa': 1203424,
 'Andrea Bocelli': 111589,
 'Andrea Gylfadóttir': 2552,
 'Andrea Radice': 238717,
 'Andreas Aleman': 429532,
 'Andreas Gabalier': 2257462,
 'Andreas Moe': 24333,
 'Andreas Weise': 1976284,
 'Andrelli': 1576966,
 'Andrew Belle': 2484,
 'Andrew Billings': 70529,
 'Andrew McMahon in the Wilderness': 180473,
 'Andrew Tan': 819237,
 'André Hazes Jr.': 6068391,
 'Andrés Calamaro': 4403311,
 'Andrés Cepeda': 4118209,
 'Andrés Suárez': 17353,
 'Andy Grammer': 99700715,
 'Andy Hui': 2439,
 'Andy Lau': 24891,
 'Andy Rivera': 4197958,
 'Andy Shauf': 76311,
 'Andy Williams': 75934323,
 'Andymori': 1167,
 'Ane Brun': 117696,
 'Anevo': 202920,
 'Angel': 63000,
 'Angela Chang': 13748,
 'Angela Torres': 98064,
 'Angeles': 633294,
 'Angelica Vale': 2383894,
 'Angelina Jordan': 69692,
 'Angeline Quinto': 6194607,
 'Angelo King': 428156,
 'Angemi': 451786,
 'Angerwolf': 11961,
 'Anggun': 80593,
 'Angie Stone': 67735,
 'Angus & Julia Stone': 9897085,
 'Angèle': 250095,
 'Ania Dabrowska': 825752,
 'Ania Wyszkoni': 54485,
 'Aniceto Molina': 27363,
 'Aniceto Molina Y La Luz Roja De San Marcos': 16391,
 'Anine Stang': 13511,
 'Anis Don Demina': 777581,
 'Anita Kerr Singers': 33254514,
 'Anitta': 337681910,
 'Anja Nissen': 199998,
 'Anji': 3250027,
 'Anjulie': 4513604,
 'Anly': 57611,
 'Anna Eriksson': 41271,
 'Anna Järvinen': 29652,
 'Anna Kendrick': 1975475,
 'Anna Naklab': 3951,
 'Anna Of The North': 60662,
 'Anna Puu': 2323594,
 'Anna Ternheim': 131886,
 'Annalisa': 2760441,
 'Anne Grete Preus': 32875,
 'Anne Linnet': 570487,
 'Anne-Marie': 158685692,
 'AnnenMayKantereit': 479478,
 'Annet Charitonová': 20285,
 'Annie Leigh': 90311,
 'Annie Lennox': 327998,
 'Anniina': 927535,
 'Annika Wells': 15762,
 'Annikki Tähti': 7975,
 'Anoflex': 246215,
 'Anonimus': 233221,
 'Anouk': 16788,
 'Ansiktet': 652832,
 'Ansis': 30936,
 'Anson Hu': 50284,
 'Anssi Kela': 124005,
 'Anstandslos & Durchgeknallt': 366589,
 'Anthony': 6938,
 'Anthony Gonzalez': 2106644,
 'Anthony Harm': 3917,
 'Antilopen Gang': 651467,
 'Antis': 1075,
 'Anton Hagman': 6651548,
 'Anton Powers': 1381168,
 'Antonello Venditti': 361693,
 'Antonio José': 27090983,
 'Antonio Orozco': 162317,
 'Antonio Rios': 95290,
 'Antony Parviainen': 45301,
 'Antti Ketonen': 1230206,
 'Antti Railio': 65216,
 'Antti Tuisku': 35956315,
 'Anu-D': 257985,
 'Anuar & Ellina': 195702,
 'Anuar Zain': 485753,
 'Anuel Aa': 427617361,
 'Anıl Piyancı': 15836,
 'Apink': 9821,
 'Apollo LTD': 10276,
 'Apres Ski Allstars': 31722,
 'April Ivy': 32160,
 'April Red 紅': 3452,
 'Apulanta': 110565,
 'Aquilo': 46574,
 'Ara Johari': 2703432,
 'Arash': 180863,
 'Arcade Fire': 1558181,
 'Arcadian': 105084,
 'Arcangel': 61393175,
 'Architechs': 97399,
 'Architrackz': 3803631,
 'Arctic Monkeys': 44240584,
 'Ardhito Pramono': 31941,
 'Ardian Bujupi': 125158,
 'Arena Hash': 28994,
 'Ares': 65623,
 'Aretha Franklin': 2116783,
 'Ari Koivunen': 37270,
 'Ari Lasso': 1155254,
 'Ariadne': 15387,
 'Ariana Grande': 777476150,
 'Ariel Camacho y Los Plebes Del Rancho': 9332574,
 'Ariel Tsai': 7967,
 'Arif': 7544465,
 'Arin Ray': 30394,
 'Arisa': 34246,
 'Arizona Jones': 3140,
 'Arja Koriseva': 47474,
 'Arkells': 27588,
 'Arlissa': 274743,
 'Armada': 11597837,
 'Arman Cekin': 4743837,
 'Armand Maulana': 20531,
 'Armand Van Helden': 38955,
 'Armando Hernandez': 11417,
 'Armin van Buuren': 17780297,
 'Armoo': 7136622,
 'Aron Brink': 51229,
 'Aron Can': 4486350,
 'Aron Hannes': 162192,
 'AronChupa': 4053157,
 'Arop': 45476,
 'Arshad Maimouni': 19571,
 'Art Garfunkel': 161104,
 'Artem x Yonas': 412670,
 'Artful Dodger': 95802,
 'Artigeardit': 245298,
 'Artists for Grenfell': 3286020,
 'Artsvik': 18562,
 'Arttu Lindeman': 7067388,
 'Arttu Wiskari': 8007080,
 'Arturo "Zambo" Cavero': 192720,
 'Arty': 65373,
 'Arvingarna': 82767,
 "As'ad Motawh": 478335,
 'Asa': 9785,
 'Asako Toki': 76396,
 'Ash Kidd': 141107,
 'Ashafar': 400606,
 'Ashanti': 39115,
 'Ashley Lovechild': 10898,
 'Aska Yang': 286311,
 'Aslove': 42874,
 'Aste': 7771276,
 'Astrid S': 89546290,
 'At17': 24666,
 'Athena': 2023218,
 'Atitude 67': 959309,
 'Atiye': 135305,
 'Atle': 68113,
 'Atmosfera': 2044337,
 'Atomic Kitten': 58698,
 'Atomic Otro Way': 55279,
 'Atomirotta': 32694,
 'Attan': 1116071,
 'Attaque 77': 641609,
 'Attractions': 46647,
 'Au/Ra': 20506,
 'Audioslave': 6444126,
 'August Alsina': 149475,
 'August Dahl': 106213,
 "Auli'i Cravalho": 20661993,
 'Aura': 81715,
 'Aurora': 336879,
 'Austin Basham': 3114,
 'Austin Lee': 7235,
 'Austin Mahone': 1213933,
 'Austyn Johnson': 1772796,
 'Av. Larco, la película': 523323,
 'Avain': 79037,
 'Avelino': 57928,
 'Aventura': 1046,
 'Avicii': 847296911,
 'Avril Lavigne': 228079,
 'Awich': 138190,
 'Axel': 340481,
 'Axel Schylström': 2493446,
 'Axos': 396286,
 'Axwell': 27596,
 'Axwell /\\ Ingrosso': 784980958,
 'Aya Nakamura': 7416569,
 'Ayben': 464021,
 'Ayda Jebat': 597595,
 'Aydın Kurtoğlu': 1767740,
 'Aylin Coşkun': 99933,
 'Ayo': 49972,
 'Ayo & Teo': 179539463,
 'Ayse Hatun Onal': 6541625,
 'Ayten Alpman': 9512,
 'Ayşegül Aldinç': 56827,
 'Azad': 1270894,
 'Azet': 22022839,
 'Aziz Harun': 376351,
 'Azlina Aziz': 28874,
 'Azucar Moreno': 31510,
 'Azzi Memo': 14645827,
 'B Young': 615995,
 'B*Witched': 103368,
 'B-Brave': 721504,
 'B.A.P': 11763,
 'B.B. King': 43396,
 'B.o.B': 92283,
 'B2K': 42517,
 'BACALL': 1772439,
 'BAD HOP': 15004,
 'BAEKHYUN': 16919,
 'BANANALEMON': 7242,
 'BASTIAN': 3951,
 'BAYNK': 50388,
 'BC Unidos': 35628,
 'BCW': 32951,
 'BEATEN FAME': 8450,
 'BEK & Wallin': 2144299,
 'BESS': 3615476,
 'BIGBANG': 7174675,
 'BJ The Chicago Kid': 1262,
 'BK': 49216,
 'BKO': 2142599,
 'BLACKPINK': 26434297,
 'BLVK JVCK': 3129,
 'BLØF': 3671952,
 'BMYE': 2010048,
 'BONNIE X CLYDE': 12681,
 'BOOM BOOM SATELLITES': 13246,
 'BOXING樂團': 41009,
 'BOY STORY': 3095,
 'BRADIO': 2853,
 'BROADHURST': 15482,
 'BROCKHAMPTON': 302335,
 'BSMG': 34258,
 'BTOB': 7744,
 'BTS': 216496126,
 'Baaba Maal': 3807,
 'Baby Bash': 16720,
 'Baby K': 16861248,
 'Bacilos': 24443459,
 'Backstreet Boys': 3892991,
 'Baco Exu do Blues': 191228,
 'Bad Bunny': 457239767,
 'Bad Gyal': 3752842,
 'BadBadNotGood': 3058,
 'Badoxa': 20774,
 'Badpojken': 71435,
 'Bae Fong': 77679,
 'Bag Raiders': 30958799,
 'Baggalútur': 389263,
 'Bahadır Tatlıöz': 2781835,
 'Bahamas': 4242,
 'Bailey May': 535134,
 'Baka Not Nice': 6028138,
 'Bakarhythm To': 2577,
 'Bakermat': 7854177,
 'Balsam Boys': 47672,
 'Bambini Di Praga': 60247,
 'Bamboo': 30063,
 'Bamse': 20959,
 'Band Aid': 80433413,
 'Band Aid 20': 79651,
 'Band Aid 30': 3104001,
 'Band of Horses': 54565,
 'Banda Conmoción': 11109,
 'Banda El Recodo': 1726613,
 'Banda Los Recoditos': 4749932,
 'Banda Neira': 2679040,
 'Banda Sinaloense MS de Sergio Lizárraga': 82139094,
 'Banda Tierra Sagrada': 217872,
 'Banda XXI': 325655,
 'Bang For The Buck': 2271047,
 'BangBros': 2122234,
 'Banks': 26170,
 'Banu Parlak': 43322,
 'Bar Z': 21162,
 'Barbra Streisand': 119286,
 'Barenaked Ladies': 32512,
 'Barnens önskejul artister': 31464,
 'Barnkammarkören': 29527,
 'Barry Manilow': 263140,
 'Bars and Melody': 1228,
 'Bart Peeters': 3057,
 'Bartofso': 1162223,
 'Barış Manço': 28126,
 'Base Ball Bear': 17907,
 'BasedBoys': 4030077,
 'Basement Jaxx': 147009,
 'Basenji': 30098,
 'Basic Tape': 516042,
 'Basim': 7389923,
 'Bassbros': 202084,
 'Basshunter': 132644,
 'Bassi Maestro': 81812,
 'Bassjackers': 2816,
 'Bastian': 110381,
 'Bastille': 21038345,
 'Battle Beast': 12364,
 'Bausa': 102232535,
 'Baustelle': 1291794,
 'Bazart': 2119204,
 'Bağzıları': 2120072,
 'Bca': 37251,
 'Bea Miller': 38563,
 'Bearson': 125946,
 'Beatrice Eli': 67095,
 'Beatrich': 99869,
 'Beatriz Luengo': 2483313,
 'Beatsteaks': 43791,
 'Bebe': 24817,
 'Bebe Rexha': 580350195,
 'Becca Adams': 13505,
 'Beck': 338781,
 'Becky G': 366797512,
 'Becky Hill': 44938,
 'Bedoes': 2622282,
 'Bee Gees': 2676736,
 'Beegie Adair & Friends': 11301,
 'Beginner': 10077143,
 'Bek Phillips': 20722,
 'Beko': 439871,
 'Belchior': 422228,
 'Belinda Carlisle': 46851,
 'Bella & Filippa': 2137685,
 'Ben Cristovao': 959718,
 'Ben DJ': 303450,
 'Ben E. King': 173483,
 'Ben Howard': 447580,
 'Ben Mitkus': 139671,
 'Ben Rector': 177833,
 'Ben Sihombing': 13606,
 'Ben&Ben': 505677,
 'Benal': 760644,
 'Benash': 16603494,
 'Benedicté': 2758,
 'Bengous': 61847,
 'Bengü': 4897047,
 'Benjamin': 55598,
 'Benjamin Beats': 4338452,
 'Benjamin Blümchen': 24375,
 'Benjamin Clementine': 2099,
 'Benjamin Francis Leftwich': 190219,
 'Benjamin Ingrosso': 7645167,
 'Benjamin Rihan': 53693,
 'Benjamín Amadeo': 46373,
 'Benji & Fede': 9762938,
 'Benni Sparks': 50722,
 'Benny Anderssons Orkester': 2057369,
 'Benny Jamz': 2290492,
 'Bente': 13503,
 'Beret': 23178689,
 'Berkay': 3001861,
 'Berkcan Güven': 225872,
 'Berksan': 448790,
 'Bermudu Divstūris': 24133,
 'Bernhoft': 29625,
 'Bet Bet': 1165,
 'Beta Radio': 7130,
 'Beth Ditto': 9807,
 'Betta Lemme': 39052,
 'Bette Midler': 3316,
 'Betty Who': 2780,
 'Betül Demir': 111585,
 'Beverly': 46833,
 'Beyoncé': 12110479,
 'Bhad Bhabie': 192643,
 'Bianca Atzei': 889770,
 'Bianca Ryan': 688415,
 'Białas': 3152543,
 'Białas, Lanek': 149212,
 'Bibi H.': 627548,
 'Biffy Clyro': 1071977,
 'Big Boi': 8916,
 'Big Boy': 1078,
 'Big Fish': 3269,
 'Big Scary': 30998,
 'Big Sean': 864370365,
 'Big Shaq': 196795965,
 'Big Sim': 7599,
 'Big Wild': 2531,
 'Big Yamo': 183191,
 'Bigflo & Oli': 20543452,
 'Bil Musa': 11876,
 'Bilal Hancı': 222851,
 'Bilal Sonses': 22686,
 'Bilderbuch': 2627693,
 'Bile-Dani': 9728,
 'Bilge Nihan': 1763717,
 'Bill Withers': 107797,
 'Billie Eilish': 989093,
 'Billie Holiday': 28518,
 "Billo's Caracas Boys": 94215,
 'Billy Currington': 10665225,
 'Billy Joel': 459319,
 'Billy Paul': 39872,
 'Billy Raffoul': 3193,
 'Bing Crosby': 105573146,
 'Bingo Players': 51558,
 'Binomio de Oro de América': 24825,
 'Biondo': 174471,
 'Bipolar Sunshine': 42566,
 'Birdy': 551492,
 'Birgir': 115218,
 'Birgitta Haukdal': 149185,
 'Birnir': 1572827,
 'Birol Giray': 6145,
 'Bishop Briggs': 6986,
 'Bispo': 205224,
 'Bizzey': 35746510,
 'Björgvin Halldórsson': 130991,
 'Björk': 65794,
 'Björk Guðmundsdóttir': 2691,
 'Björn Skifs': 51908,
 'Bjørnskov': 24907,
 'Black': 155821,
 'Black Box': 46094,
 'Black Dog Bone': 76630,
 'Black M': 2728836,
 'Black Saint': 712295,
 'BlackJack': 210577,
 'Blackstreet': 4236187,
 'Blak': 12854400,
 'Blake Shelton': 349832,
 'Blanche': 7194228,
 'Blas Cantó': 1258901,
 'Bleachers': 3235,
 'Blen': 18213,
 'Bliss n Eso': 17766040,
 'Blizzy': 247415,
 'Block B': 3135,
 'Blonde': 1355945,
 'Blonde Redhead': 13811,
 'Blossoms': 34243,
 'Blouson Chiemi': 88413,
 'Blu Cantrell': 286569,
 'Blue': 103414,
 'Blue Cafe': 62614,
 'Blue Cafe & Kornelia Mzyk': 13957,
 'Blue Street Players': 39317,
 'Blue Swede': 50184,
 'Blue Öyster Cult': 1404687,
 'Blur': 390789,
 'Bo Kaspers Orkester': 481450,
 'BoA': 3712,
 'Bob B. Soxx & The Blue Jeans': 437598,
 'Bob Dylan': 404671,
 'Bob Marley & The Wailers': 529827,
 'Bob Pressner': 188347,
 'Bob Sinclar': 416920,
 'Bobby "Boris" Pickett': 214616,
 'Bobby "Boris" Pickett & The Crypt-Kickers': 1828455,
 'Bobby Darin': 80565,
 'Bobby Helms': 24755987,
 'Bobby McFerrin': 198766,
 'Bobby Vee': 3924,
 'Bobby Vinton': 36295,
 'Boef': 139713545,
 'Boehm': 261552,
 'Bohemia Suburbana': 11829,
 'Bokoesam': 1628656,
 'Boku no Lyric no Boyomi': 10999,
 'Bolier': 63398,
 'Bollebof': 69355,
 'Bolly': 5146,
 'Bomba Estéreo': 508085,
 'Bombai': 3986369,
 'Bombay Bicycle Club': 41342,
 'Bon Iver': 937071,
 'Bon Jovi': 950549,
 'Bonde R300': 18600109,
 'Boney M.': 10237774,
 'Bonez MC': 149845585,
 'Bonnie Tyler': 850463,
 'Bonny Cepeda': 11079,
 'Bonny Lovy': 1236187,
 'Bonobo': 765516,
 'Boo Seeka': 18252,
 'Booba': 92133682,
 'Boomdabash': 4852947,
 'Boostee': 6212177,
 'Boreal': 132538,
 'Boris René': 2619389,
 'Borixon': 79401,
 'Bosx1ne': 521447,
 'Boudewijn de Groot': 14401,
 'Bovea Y Sus Vallenatos': 13649,
 'BowlLane Slick': 4359,
 'Boyat': 134269,
 'Boys Under The Moon': 6624,
 'Boyz II Men': 432542,
 'Boyzone': 7937310,
 'Brad Paisley': 9121,
 'Brainstorm': 1260,
 'Brandon Beal': 905143,
 'Brandyn Burnette': 37376,
 'Branko': 1607,
 'Brantley Gilbert': 1363771,
 'Breakbot': 48687,
 'Breathe Carolina': 92738,
 'Brenda Lee': 79735942,
 'Brendan Murray': 17109,
 'Brett Eldredge': 2235479,
 'Brett Young': 54438316,
 'Brian Eno': 1280,
 'Brian Ligon': 4393,
 'Brian McKnight': 40370,
 'Briga': 1886624,
 'Brings': 339712,
 'Britney Spears': 19662490,
 'Bro': 1981658,
 'Broadcast': 26385,
 'Broederliefde': 68437247,
 'Broertje': 810793,
 'Broiler': 6920543,
 'Broken Back': 924126,
 'Brolle': 687341,
 'Bronco': 448941,
 'Brooke Candy': 44482,
 'Bruce Reitherman': 3303,
 'Bruce Springsteen': 9011653,
 'Bruninho & Davi': 44451635,
 'Bruno & Barretto': 32677,
 'Bruno & Marrone': 10059859,
 'Bruno Mars': 1915554926,
 'Bruno Martini': 27013336,
 'Bruno Wintzell': 522021,
 'Brunori Sas': 541201,
 'Bryan Adams': 7305328,
 'Bryant Myers': 20904622,
 'Bryson Tiller': 218894798,
 'Brytiago': 49500976,
 'Brädi': 4254984,
 'Bubbi Morthens': 29679,
 'Bugzy Malone': 5930769,
 'Buitres': 3610,
 'Bulin 47': 31824,
 'Bunbury': 223149,

In [111]:
len(artist_list)

6628

In [112]:
%%time
dict_val = {}
for i in artist_list[0:10]:
    reg_count = len(df[df['Artist'] == i].groupby('Region').sum()['Streams'])
    dict_reg = {}
    for j in np.arange(1,reg_count+1):
        dict_reg[df[df['Artist'] == i].groupby('Region').sum()['Streams'].index[j-1]] = df[df['Artist'] == i].groupby('Region').sum()['Streams'][j-1]
    dict_val[i] = dict_reg

CPU times: user 8.25 s, sys: 77.6 ms, total: 8.33 s
Wall time: 8.35 s

In [113]:
dict_val

{'#TocoParaVos': {'ar': 2307837, 'uy': 1177893},
 '$uicideBoy$': {'fi': 44258},
 '*NSYNC': {'at': 167900,
  'au': 89263,
  'be': 25890,
  'ca': 148178,
  'ch': 118755,
  'cz': 7169,
  'de': 2324093,
  'dk': 34675,
  'es': 27258,
  'gb': 116599,
  'global': 2985809,
  'gr': 2130,
  'hk': 5020,
  'hu': 20588,
  'it': 114623,
  'lv': 1016,
  'my': 3867,
  'nl': 144729,
  'nz': 12018,
  'ph': 40039,
  'pt': 2986,
  'sg': 10304,
  'us': 1081292},
 '-M-': {'fr': 43037},
 '070 Shake': {'no': 31035},
 '100%': {'tw': 2465},
 '101Barz': {'nl': 81269},
 '10cm': {'hk': 10008, 'id': 10164, 'my': 74924, 'sg': 75688, 'tw': 76360},
 '12:00': {'is': 6706},
 '13 Block': {'fr': 853726}}

In [114]:
df.head()

,Position,Track Name,Artist,Streams,Date,Region
0,1,Reggaetón Lento (Bailemos),CNCO,19272,2017-01-01,ec
1,2,Chantaje,Shakira,19270,2017-01-01,ec
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,2017-01-01,ec
3,4,Vente Pa' Ca,Ricky Martin,14954,2017-01-01,ec
4,5,Safari,J Balvin,14269,2017-01-01,ec

In [115]:
df['Score'] = df['Position'].apply(lambda x: 201-x)

In [116]:
df.head()

,Position,Track Name,Artist,Streams,Date,Region,Score
0,1,Reggaetón Lento (Bailemos),CNCO,19272,2017-01-01,ec,200
1,2,Chantaje,Shakira,19270,2017-01-01,ec,199
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,2017-01-01,ec,198
3,4,Vente Pa' Ca,Ricky Martin,14954,2017-01-01,ec,197
4,5,Safari,J Balvin,14269,2017-01-01,ec,196

In [117]:
df['Position'].sum()

325654673

In [118]:
df['Score'].sum()

365893867

In [119]:
df['Score'] = df['Score']*df['Streams']

In [120]:
df.head()

,Position,Track Name,Artist,Streams,Date,Region,Score
0,1,Reggaetón Lento (Bailemos),CNCO,19272,2017-01-01,ec,3854400
1,2,Chantaje,Shakira,19270,2017-01-01,ec,3834730
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,2017-01-01,ec,3120678
3,4,Vente Pa' Ca,Ricky Martin,14954,2017-01-01,ec,2945938
4,5,Safari,J Balvin,14269,2017-01-01,ec,2796724

In [121]:
df.sort_values('Score',ascending=False)[0:10]

,Position,Track Name,Artist,Streams,Date,Region,Score
3145443,1,Despacito (Featuring Daddy Yankee),Luis Fonsi,11381520,2017-05-27,global,2276304000
3128643,1,Shape of You,Ed Sheeran,9891056,2017-03-03,global,1978211200
3145643,1,Despacito (Featuring Daddy Yankee),Luis Fonsi,9849173,2017-05-28,global,1969834600
3128843,1,Shape of You,Ed Sheeran,9603434,2017-03-04,global,1920686800
3129243,1,Shape of You,Ed Sheeran,8900049,2017-03-07,global,1780009800
3129843,1,Shape of You,Ed Sheeran,8849461,2017-03-10,global,1769892200
3129443,1,Shape of You,Ed Sheeran,8738426,2017-03-08,global,1747685200
3129643,1,Shape of You,Ed Sheeran,8695555,2017-03-09,global,1739111000
3130043,1,Shape of You,Ed Sheeran,8664792,2017-03-11,global,1732958400
3145243,1,Despacito - Remix,Luis Fonsi,8525474,2017-05-26,global,1705094800

In [122]:
df.groupby(['Track Name']).sum().sort_values(['Score'],ascending=False)[0:10]

                                    Position     Streams         Score
Track Name
Shape of You                          301513  2993988783  576014557137
Despacito - Remix                     477232  1829621841  344485342045
Despacito (Featuring Daddy Yankee)    816152  1460802540  254312091238
rockstar                              127973  1260181617  248789325765
Something Just Like This              725122  1386258295  241040803597
Unforgettable                         722129  1366919951  240270731063
HUMBLE.                               854060  1311243745  233760898076
I'm the One                           548303  1254196301  226064557026
New Rules                             238751  1119958003  211314564334
XO TOUR Llif3                         815686  1171827725  205878394856

In [123]:
df.groupby(['Artist']).sum(['Score']).sort_values(['Score'],ascending=False)[0:10]

                  Position     Streams          Score
Artist
Ed Sheeran        10534351  8913973976  1390666035405
Luis Fonsi         1442101  3555514919   646245714776
The Chainsmokers   5304084  4292590087   643617121285
Drake              4679189  4523630992   604546555969
Post Malone        2466648  3700404149   597288981851
Kendrick Lamar     2471880  3570665303   548960031600
J Balvin           1986826  2494735971   401534994564
DJ Khaled          1171546  2236224259   392427155515
Imagine Dragons    2727838  2322921399   364306086308
Calvin Harris      3110608  2397708371   355949623981

In [124]:
top_score_songs = df.groupby(['Track Name']).sum(['Score']).sort_values(['Score'],ascending=False)[0:10].index.tolist()

In [125]:
#Top 10 artist as per score of their song
for i in top_score_songs:
    print(df[df['Track Name'] == i]['Artist'].min())

Ed Sheeran
Luis Fonsi
Luis Fonsi
Post Malone
The Chainsmokers
French Montana
Kendrick Lamar
DJ Khaled
Becca Adams
Lil Uzi Vert

In [126]:
#Top 10 artist as per score of their song
df.groupby(['Artist']).sum(['Score']).sort_values(['Score'],ascending=False)[0:10].index

Index(['Ed Sheeran', 'Luis Fonsi', 'The Chainsmokers', 'Drake', 'Post Malone',
       'Kendrick Lamar', 'J Balvin', 'DJ Khaled', 'Imagine Dragons',
       'Calvin Harris'],
      dtype='object', name='Artist')

In [127]:
track_list = df['Track Name'].unique().tolist()

In [153]:
def track_to_region(track_name):
    if track_name in track_list:
        return dict((x,y) for x,y in tuple(zip(df[df['Track Name'] == track_name].groupby(['Region']).sum().index.tolist(),df[df['Track Name'] == track_name].groupby(['Region']).sum().values[:,1].tolist())))
    else:
        print('Track not found')

In [156]:
def track_to_month(track_name):
    if track_name in track_list:
        return dict((x,y) for x,y in tuple(zip(df[(df['Track Name'] == track_name) & (df['Year'] == '2017')].groupby(['Month_name']).sum().index.tolist(),df[(df['Track Name'] == track_name) & (df['Year'] == '2017')].groupby(['Month_name']).sum().values[:,1])))
    else:
        print('Track not found')

In [131]:
df['Year'] = df['Date'].apply(lambda x : x.split('-')[0])
df['Date'] = pd.to_datetime(df['Date'])
df['Month_name'] = df['Date'].dt.month_name()

In [132]:
df.head()

,Position,Track Name,Artist,Streams,Date,Region,Score,Year,Month_name
0,1,Reggaetón Lento (Bailemos),CNCO,19272,2017-01-01,ec,3854400,2017,January
1,2,Chantaje,Shakira,19270,2017-01-01,ec,3834730,2017,January
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,2017-01-01,ec,3120678,2017,January
3,4,Vente Pa' Ca,Ricky Martin,14954,2017-01-01,ec,2945938,2017,January
4,5,Safari,J Balvin,14269,2017-01-01,ec,2796724,2017,January

In [148]:
df[(df['Track Name'] == 'Shape of You') & (df['Year'] == '2017')].groupby(['Month_name']).sum().values[:,1]

array([340035736, 166852553, 135624071, 407227623, 366007170, 199073911,
       219295280, 469111248, 269169687, 116052127, 127884795, 137980741],
      dtype=int64)

In [151]:
track_to_month('Shape of You')

(('April', 340035736),
 ('August', 166852553),
 ('December', 135624071),
 ('February', 407227623),
 ('January', 366007170),
 ('July', 199073911),
 ('June', 219295280),
 ('March', 469111248),
 ('May', 269169687),
 ('November', 116052127),
 ('October', 127884795),
 ('September', 137980741))

In [85]:
df['Date'] = pd.to_datetime(df['Date'])

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3440540 entries, 0 to 3441196
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   Position    int64
 1   Track Name  object
 2   Artist      object
 3   Streams     int64
 4   Date        datetime64[ns]
 5   Region      object
 6   Score       int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 210.0+ MB

In [90]:
df['Month_name'] = df['Date'].dt.month_name()

In [91]:
df.head()

,Position,Track Name,Artist,Streams,Date,Region,Score,Year,Month_name
0,1,Reggaetón Lento (Bailemos),CNCO,19272,2017-01-01,ec,3854400,January,January
1,2,Chantaje,Shakira,19270,2017-01-01,ec,3834730,January,January
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,2017-01-01,ec,3120678,January,January
3,4,Vente Pa' Ca,Ricky Martin,14954,2017-01-01,ec,2945938,January,January
4,5,Safari,J Balvin,14269,2017-01-01,ec,2796724,January,January

In [93]:
df['Year'] = df['Date'].apply(lambda x : x.split('-')[0])

AttributeError: 'Timestamp' object has no attribute 'split'

In [154]:
track_to_region('Shape of You')

{'ar': 41734990,
 'at': 5730722,
 'au': 51946735,
 'be': 11255872,
 'bo': 1866375,
 'br': 97680541,
 'ca': 47971559,
 'ch': 9933459,
 'cl': 29684703,
 'co': 14826643,
 'cr': 7348470,
 'cz': 4313689,
 'de': 97689020,
 'dk': 24456121,
 'do': 2038157,
 'ec': 5256420,
 'ee': 874398,
 'es': 60853374,
 'fi': 15490841,
 'fr': 46245081,
 'gb': 132102967,
 'global': 1490812208,
 'gr': 1748346,
 'gt': 2305402,
 'hk': 5042866,
 'hn': 1791363,
 'hu': 3526256,
 'id': 21424856,
 'ie': 11480510,
 'is': 1494071,
 'it': 38335325,
 'jp': 6690019,
 'lt': 904314,
 'lu': 544631,
 'lv': 888066,
 'mx': 87592084,
 'my': 11881558,
 'nl': 56167880,
 'no': 31152940,
 'nz': 13242307,
 'pa': 2112146,
 'pe': 16174445,
 'ph': 57836288,
 'pl': 16783834,
 'pt': 8607798,
 'py': 2438885,
 'se': 63869649,
 'sg': 15635592,
 'sk': 1266491,
 'sv': 1569087,
 'tr': 18442317,
 'tw': 7767759,
 'us': 282319891,
 'uy': 2839462}